# Generated by Django 4.1.7 on 2023-03-30 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('album_name', models.CharField(max_length=100, unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.artist')),
                ('songs', models.ManyToManyField(to='musicplayer.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='genere',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicplayer.genre'),
            preserve_default=False,
        ),
    ]
