# Generated by Django 4.1.7 on 2023-03-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_genre_artist_url_song_url_album_song_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='1', upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
