# Generated by Django 4.1.7 on 2023-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0004_album_image_artist_image_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='price',
        ),
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
