# Generated by Django 4.1.7 on 2023-04-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0009_order_paid_order_signature_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.song'),
        ),
    ]
