# Generated by Django 4.1.7 on 2023-04-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplayer', '0012_alter_album_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('image', models.ImageField(upload_to='uploads')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.genre')),
            ],
        ),
    ]
