# Generated by Django 4.1.7 on 2023-04-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplayer', '0016_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
