# Generated by Django 4.1.7 on 2023-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0017_song_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
