# Generated by Django 4.1.7 on 2023-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
