# Generated by Django 4.1.7 on 2023-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0020_comment_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
