# Generated by Django 4.1.7 on 2023-04-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0023_blog_tags_song_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='url',
        ),
    ]
