# Generated by Django 4.1.7 on 2023-04-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0024_remove_tags_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
